version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 3306:3306

  config:
    image: dvmflstm/config
    depends_on:
      - mysql
    environment:
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8888:8888

  registry:
    image: dvmflstm/registry
    depends_on:
      - config
      - mysql
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
    ports:
      - 8761:8761

  gateway:
    image: dvmflstm/gateway
    depends_on:
      - config
      - registry
      - mysql
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
    ports:
      - 8080:8080

  auth:
    image: dvmflstm/auth
    depends_on:
      - config
      - registry
      - mysql
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      jwt.secretKey: "geunyoung_jwt_secret"
    ports:
      - 8081:8080

  diet:
    image: dvmflstm/diet
    depends_on:
      - config
      - registry
      - mysql
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
    ports:
      - 8082:8080

  exercise:
    image: dvmflstm/exercise
    depends_on:
      - config
      - registry
      - mysql
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
    ports:
      - 8083:8080

  statistics:
    image: dvmflstm/statistics
    depends_on:
      - config
      - registry
      - mysql
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
    ports:
      - 8084:8080

