server:
  port: 8761
spring:
  application:
    name: "discovery-server"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
